/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as PropostaIdRouteImport } from './routes/proposta.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedOportunidadesIdRouteImport } from './routes/_authenticated/oportunidades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropostaIdRoute = PropostaIdRouteImport.update({
  id: '/proposta/$id',
  path: '/proposta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedOportunidadesIdRoute =
  AuthenticatedOportunidadesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOportunidadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRouteWithChildren
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/oportunidades/$id': typeof AuthenticatedOportunidadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/oportunidades'
    | '/orcamentos'
    | '/proposta/$id'
    | '/clientes/$id'
    | '/oportunidades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/oportunidades'
    | '/orcamentos'
    | '/proposta/$id'
    | '/clientes/$id'
    | '/oportunidades/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/oportunidades'
    | '/_authenticated/orcamentos'
    | '/proposta/$id'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/oportunidades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PropostaIdRoute: typeof PropostaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/proposta/$id': {
      id: '/proposta/$id'
      path: '/proposta/$id'
      fullPath: '/proposta/$id'
      preLoaderRoute: typeof PropostaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/oportunidades/$id': {
      id: '/_authenticated/oportunidades/$id'
      path: '/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof AuthenticatedOportunidadesIdRouteImport
      parentRoute: typeof AuthenticatedOportunidadesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedOportunidadesRouteChildren {
  AuthenticatedOportunidadesIdRoute: typeof AuthenticatedOportunidadesIdRoute
}

const AuthenticatedOportunidadesRouteChildren: AuthenticatedOportunidadesRouteChildren =
  {
    AuthenticatedOportunidadesIdRoute: AuthenticatedOportunidadesIdRoute,
  }

const AuthenticatedOportunidadesRouteWithChildren =
  AuthenticatedOportunidadesRoute._addFileChildren(
    AuthenticatedOportunidadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRouteWithChildren
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRouteWithChildren,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PropostaIdRoute: PropostaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
